### ISSUE TITLE
- Version: 2012-10-17 getting parsed as a date

### ISSUE THREAD

**Issue by studds** [yyolk/cloudformation-js-yaml-schema#20]
I've got a template:

```yaml
Resources:
    Function:
        Type: 'AWS::Serverless::Function'
        Properties:
            CodeUri: code/
            Handler: code.handler
            Runtime: nodejs8.10
            Policies:
                - Version: 2012-10-17
                  Statement:
                      - Effect: Allow
                        Action: 'ses:SendRawEmail'
                        Resource: !Sub 'arn:aws:ses:*:*:identity/*'
```

When I read it and then write it out again, `- Version: 2012-10-17` becomes `- Version: 2012-10-17T00:00:00.000Z`, which is invalid. `- Version: '2012-10-17'` is fine, but I'm hoping there's a way to make this more robust, and simply not parse the dates.

Any hints?
